# Introduction to PyTorch

In this tutorial, we will use PyTorch. A few words of introduction to what PyTorch does. We will dive into relevant portions of PyTorch in detail throughout this course.

## What is PyTorch?

PyTorch is a scientific computing (it is much more general than a toolbox for machine learning!) package developed primarily by Facebook.

In this tutorial, let us look at the building blocks of PyTorch.

This notebook is just a simple introduction. We'll delve deep into it as we go along..

## Tensors

Tensors are the core building blocks of PyTorch. Think of them like turbocharged `numpy.ndarray`. They run on GPUs and they come with more bells and whistles that a normal `numpy.ndarray` cannot do.

Oh and they can track gradients and other things.

In [1]:
from __future__ import print_function
import torch

Let us initialize an empty uninitialized tensor. 

In [2]:
x = torch.empty(3, 4)
print(x)

tensor([[ 3539.7324,     0.0000,  3539.7324,     0.0000],
        [    0.0000,     0.0000,     0.0000,     0.0000],
        [    0.0000,     0.0000,     0.0000,     0.0000]])


Let us construct a tensor with random values in it.

In [3]:
x = torch.rand(3, 4)
print(x)

tensor([[ 0.1034,  0.4959,  0.9990,  0.4371],
        [ 0.8714,  0.8919,  0.6877,  0.2359],
        [ 0.4840,  0.6405,  0.9767,  0.8828]])


Let us look at the size of the tensor that we defined in the previous cell.

In [4]:
x.size()

torch.Size([3, 4])

## Operations on tensors

In [5]:
a = torch.ones(2, 3)
b = torch.ones(2, 3)

s = a + 2*b
print(s)

d = a - 3*b
print(d)

tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.]])
tensor([[-2., -2., -2.],
        [-2., -2., -2.]])


You can use standard NumPy-like indexing with all bells and whistles!

In [6]:
print(d[:, 1])

tensor([-2., -2.])


In [7]:
print(d[1, :])

tensor([-2., -2., -2.])


## Converting to NumPy arrays

In [8]:
b_np = b.numpy()
print(b_np)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print('Type of b', type(b))
print('Type of b_np', type(b_np))

Type of b <class 'torch.Tensor'>
Type of b_np <class 'numpy.ndarray'>


## Converting to torch tensors

In [10]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

In [11]:
print(a)

[1. 1. 1. 1. 1.]


In [12]:
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)


Till now, it should not be a surprise for anyone used to `numpy`. Mostly, it has been functionining like `numpy`. Let us look at how they are different now.

I mentioned earlier that they work on GPUs as well. 

Let us see how easy it is!

## CUDA Tensors

First, let us check if your machine has GPU and CUDA is enabled. It is easily done using `torch.cuda.is_available()`.

While we are at it, let us also look at how many GPUs we have. This is done using `torch.cuda.device_count()`.

In [13]:
torch.cuda.is_available()

True

In [14]:
torch.cuda.device_count()

8

A device is chosen using `torch.device("cuda")`.

In [15]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 1.1034,  1.4959,  1.9990,  1.4371],
        [ 1.8714,  1.8919,  1.6877,  1.2359],
        [ 1.4840,  1.6405,  1.9767,  1.8828]], device='cuda:0')
tensor([[ 1.1034,  1.4959,  1.9990,  1.4371],
        [ 1.8714,  1.8919,  1.6877,  1.2359],
        [ 1.4840,  1.6405,  1.9767,  1.8828]], dtype=torch.float64)


There is another useful shortcut worth knowing. 

Calling `.cuda()` on a tensor moves the tensors to the GPUs. For a lot of image classification exercises, computing on CPUs is extremely slow.

`.cuda()` works on a lot of things - models, tensors etc.

In [16]:
x = torch.ones([2, 2])
x.cuda()

tensor([[ 1.,  1.],
        [ 1.,  1.]], device='cuda:0')