# Automatic differentiation

Automatic differentiation is a core component of `torch`. `autograd` is essential to understand how neural networks can be trained. So, let us look at a few simple examples to understand how `autograd` works.

`autograd` in `torch` provides automatic differentiation capabilities for all operations in tensor. It is an essential part to understand how backpropagation works in `torch`.

Let us look at a few examples to carefully understand what this is all about.

Let us start with an example from our previous notebook and define a tensor.

In [1]:
import torch

An important part of tensors in PyTorch is the ability to track operations as we go along. 

If we set its attribute `.requires_grad` as `True`, it starts to track all operations on it. When we finish your computation you can call `.backward()` and have all the gradients computed automatically. The gradient for this tensor will be accumulated into `.grad` attribute.

In [2]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
print(x)

tensor([ 1.,  2.,  3.])


Let us do a few operations on the tensor to see what it is all about.

In [3]:
y = x + 2
z = y*y
print(z)

tensor([  9.,  16.,  25.])


In [4]:
zmean = z.mean()
print(zmean)

tensor(16.6667)


## Computing gradients

Now that we have computed a single value - `zmean` from a tensor `z`, let us run backpropagation and compute the gradients.

In [5]:
zmean.backward()

Let us look at the gradients now.

In [6]:
print(x.grad)

tensor([ 2.0000,  2.6667,  3.3333])


Of course, `torch` computed the gradients for us. Let us do this with hand and make sure we understand this well.

\begin{eqnarray}
y &= x + 2 \\
z &= y^2 \\
z_{mean} &= \sum_{i=1}^3 z_i
\end{eqnarray}

For simple functions like we defined above, we can compute it by hand. However, for complicated functions of several variables, it is a challenge to compute it by hand. That is where we see the true power of `autograd`.

In the next few notebooks, we will see the power of automatic differentiation.

A final note: Although this tutorial uses `torch` to illustrate automatic differentiation, backward propagation and other concepts, these concepts are true for your favorite deep learning package.